version: "3.8"

networks:
  inception:
    driver: "bridge"
    external: false

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/db

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    hostname: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    hostname: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  nginx:
    depends_on:
     - wordpress
    container_name: nginx
    image: nginx
    hostname: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  redis:
    depends_on:
      - wordpress
    container_name: redis
    image: redis
    hostname: redis
    build: ./requirements/bonus/redis
    volumes:
     - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  
  adminer:
    depends_on:
      - mariadb
    container_name: adminer
    image: adminer
    hostname: adminer
    build: ./requirements/bonus/adminer
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  
  ftp:
    depends_on:
      - wordpress
    container_name: ftp
    image: ftp
    hostname: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  static_page:
    depends_on:
      - nginx
    container_name: static_page
    image: static_page
    hostname: static_page
    build: ./requirements/bonus/static_page
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    hostname: cadvisor
    build: ./requirements/bonus/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped