version: "3.8"

networks:
  inception:
    driver: "bridge"

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/db

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    ports:
      - "80:80"
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: on-failure

  nginx:
    depends_on:
     - wordpress
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: on-failure

