version: "3.8"

networks:
  inception:
    driver: "bridge"
    external: false

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/db

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    hostname: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress
    hostname: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  nginx:
    depends_on:
     - wordpress
    container_name: nginx
    image: nginx
    hostname: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  redis:
    depends_on:
      - wordpress
    container_name: redis
    image: redis
    hostname: redis
    build: ./requirements/bonus/redis
    volumes:
     - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  
  adminer:
    depends_on:
      - mariadb
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - inception
    restart: unless-stopped
  
  # ftp:
  #   depends_on:
  #     - wordpress
  #   container_name: ftp
  #   build: ./requirements/bonus/ftp
  #   volumes:
  #     - wp:/var/www/html
  #   networks:
  #     - inception
  #   restart: unless-stopped