version: "3.8"

services:
  # nginx:
  #   depends_on:
  #    - wordpress
      # container_name: nginx
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"
  #   env_file:
  #     - .env
  #   restart: always

  mariadb:
    container_name: mariadb
    
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    restart: always

  # wordpress:
  #   depends_on:
  #     - mariadb
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - wp:
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  db:

  wp: