version: "3.8"

networks:
  inception:
    driver: "bridge"
    external: false

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/wp

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bfranco/data/db

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  nginx:
    depends_on:
     - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  # redis:
  #   depends_on:
  #     - wordpress
  #   container_name: redis
  #   build: ./requirements/bonus/redis
  #   volumes:
  #    - wp:/var/www/html
  #   networks:
  #     - inception
  #   restart: on-failure
  
  # adminer:
  #   depends_on:
  #     - mariadb
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - inception
  #   restart: on-failure