FROM debian:buster

EXPOSE 3306

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y mariadb-server
 
# COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./conf/db_setup.sql /db_setup.sql
COPY ./tools/mariadb.sh /mariadb.sh

RUN chmod +x /mariadb.sh
RUN chmod 777 /db_setup.sql
WORKDIR /var/lib/mysql

ENTRYPOINT [ "/mariadb.sh" ]

# CMD ["mysql -u root -p$DB_PASSWORD "]
