version: "2.3.3"

services:
  nginx:
    depends_on:
     - wordpress
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: always

  mariadb:
    build: ./mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./wordpress
    ports:
      - "80:80"
    volumes:
      - wp:
    env_file:
      - .env
    restart: always

volumes:
  db:

  wp: