FROM debian:bullseye

EXPOSE 20 21 22
EXPOSE 30000-30010

ENV FTP_USER=$FTP_USER
ENV FTP_PASSWORD=$FTP_PASSWORD

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y vsftpd ftp

RUN mkdir -p /var/run/vsftpd/empty

COPY ./tools/ftp.sh /ftp.sh
COPY ./conf/vsftpd.conf /vsftpd.conf
RUN chmod +x /ftp.sh
RUN chmod 777 /vsftpd.conf

ENTRYPOINT [ "/ftp.sh" ]

CMD [ "/usr/sbin/vsftpd", "/etc/vsftpd.conf" ]