FROM debian:bullseye

EXPOSE 8080

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y wget mariadb-client php7.4 php7.4-fpm php7.4-mysql

RUN mkdir -p /var/www/html
RUN chown -R www-data:www-data /var/www/html
RUN mkdir -p /run/php

COPY ./tools/adminer.sh /adminer.sh
RUN chmod +x /adminer.sh

RUN sed -i 's/listen = \/run\/php\/php7.4-fpm.sock/listen = 8080/g' /etc/php/7.4/fpm/pool.d/www.conf

WORKDIR /var/www/html

ENTRYPOINT [ "/adminer.sh" ]

CMD ["/usr/sbin/php-fpm7.4", "-F"]