FROM debian:bullseye

EXPOSE 9000
EXPOSE 6379

ENV WP_TITLE=$WP_TITLE
ENV WP_ADMIN_USER=$WP_ADMIN_USER
ENV WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
ENV WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
ENV WP_USER=$WP_USER
ENV WP_PASSWORD=$WP_PASSWORD
ENV WP_EMAIL=$WP_EMAIL
ENV WP_LOCALE=$WP_LOCALE
ENV WP_VERSION=$WP_VERSION
ENV DB_HOST=$DB_HOST

COPY ./tools/wp.sh /wp.sh
RUN chmod +x /wp.sh

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl mariadb-client php7.4 php7.4-fpm php7.4-mysql php7.4-redis

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv ./wp-cli.phar /usr/local/bin/wp
RUN mkdir -p /var/www/html
RUN chown -R www-data:www-data /var/www/html
RUN sed -i 's/listen = \/run\/php\/php7.4-fpm.sock/listen = 9000/g' /etc/php/7.4/fpm/pool.d/www.conf
WORKDIR /var/www/html

ENTRYPOINT [ "/wp.sh" ]

CMD ["/usr/sbin/php-fpm7.4", "-F"]
