FROM debian:bookworm

EXPOSE 9000

ENV WP_TITLE=$WP_TITLE
ENV WP_ADMIN_USER=$WP_ADMIN_USER
ENV WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
ENV WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
ENV WP_USER=$WP_USER
ENV WP_PASSWORD=$WP_PASSWORD
ENV WP_EMAIL=$WP_EMAIL
ENV WP_LOCALE=$WP_LOCALE
ENV WP_VERSION=$WP_VERSION
ENV DB_HOST=$DB_HOST

COPY ./tools/wp.sh /wp.sh
RUN chmod +x /wp.sh

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y curl mariadb-client php php-fpm php-mysql

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv ./wp-cli.phar /usr/local/bin/wp
RUN mkdir -p /var/www/html
RUN chown -R www-data:www-data /var/www/html
RUN echo "listen = 9000" >> /etc/php/8.2/fpm/pool.d/www.conf
WORKDIR /var/www/html

ENTRYPOINT [ "/wp.sh" ]

CMD ["/usr/sbin/php-fpm8.2", "-F"]
