FROM debian:bullseye

EXPOSE 8888

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y wget
RUN wget -O cadvisor https://github.com/google/cadvisor/releases/download/v0.47.2/cadvisor-v0.47.2-linux-amd64
RUN chmod +x cadvisor
RUN mv cadvisor /usr/bin

COPY ./tools/cadvisor.sh /cadvisor.sh
RUN chmod +x /cadvisor.sh

ENTRYPOINT [ "/cadvisor.sh" ]

CMD [ "cadvisor", "-logtostderr" ,"-port=8888"]