FROM debian:bullseye

EXPOSE 3000

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y nginx openssl

COPY ./conf/nginx.conf /etc/nginx/sites-enabled/nginx.conf
COPY ./tools/nginx.sh /nginx.sh

RUN chmod +x /nginx.sh

WORKDIR /var/www/html

ENTRYPOINT [ "/nginx.sh" ]

CMD ["nginx", "-g", "daemon off;"]