FROM debian:buster

EXPOSE 443

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./tools/nginx.sh /nginx.sh

RUN chmod +x /nginx.sh

WORKDIR /var/www/html

ENTRYPOINT [ "/nginx.sh" ]

CMD ["nginx", "-g", "daemon off;"]