CREATE DATABASE inception;
CREATE USER 'bfranco'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON inception.* TO 'bfranco'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '12345';
