CREATE DATABASE IF NOT EXISTS inception;
CREATE USER IF NOT EXISTS 'bfranco'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON inception.* TO 'bfranco'@'%';
FLUSH PRIVILEGES;
-- ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';