FROM debian:bullseye

EXPOSE 6379

RUN apt-get update -y && apt-get upgrade -y
RUN apt install -y redis-server

COPY ./tools/redis.sh /redis.sh
RUN chmod +x /redis.sh

ENTRYPOINT [ "/redis.sh" ]

CMD ["redis-server", "--protected-mode", "no"]